### ISSUE TITLE
Bug in fetch script: wrong OS for mac

### ISSUE THREAD

**Issue by glennj** [exercism/canonical-data-syncer#27]
In the fetch script, for "Darwin" platform, the OS variable is set to "mac". However, the platform part of the released tarball is "**macosx**".

Either the fetch script or the build process needs to be updated.

**Comment by glennj** [comment]
Other than that, the tool is working well for me: going through the very tedious process of verifying and accepting all the implemented tests in the  Tcl track.

**Comment by ErikSchierboom** [comment]
@glennj Wait for a sec! We'll submit a PR soon :)

**Comment by ErikSchierboom** [comment]
Which you can build on.

**Comment by ErikSchierboom** [comment]
@glennj Thanks for reporting! Fixed in https://github.com/exercism/canonical-data-syncer/pull/28

**Comment by ErikSchierboom** [comment]
New release is being built: https://github.com/exercism/canonical-data-syncer/actions/runs/297974068
