### ISSUE TITLE
CLI feature request: flag providing path to non-transient problem-specifications repo

### ISSUE THREAD

**Issue by coriolinus** [exercism/canonical-data-syncer#47]
It's cool that, left to its own devices, the canonical data syncer shallow-clones the problem-specifications repo into a temporary folder, then cleans up after itself. However, this is somewhat wasteful of bandwidth, even though it's normally fast.

If someone has a permanent problem-specifications repo, then it would be nice if they could provide its location to the syncer, giving the syncer permission to do essentially:

```bash
cd "$problem_specifications"
git checkout -- . # clear out any temporary modifications
git checkout master # or main, whatever,
git pull
```

**Comment by ee7** [comment]
I agree that this could be nice, even if just for responsiveness. It currently just does the simplest thing that will always work.

Quickly testing on a not-so-great connection:
```shell
git clone --depth 1 https://github.com/exercism/problem-specifications.git 
```
takes about 1.8 s, compared to about 0.7 s for a `git pull`.

> ```shell
> git checkout -- . # clear out any temporary modifications
> ```

This silently and non-interactively discards changes to the working directory, which we probably don't want to do even the location is passed explicitly - people could lose uncommitted changes.

We could implement it with interaction, e.g.:
```
[problem-specifications working directory] has uncommitted changes, discard them and continue anyway? [y/N]
y
You're going to lose these changes, are you really sure? [y/N]
[insert git diff]
y
```

But perhaps a good first implementation of this could just fail if we couldn't `git checkout master`.

**Comment by coriolinus** [comment]
> But perhaps a good first implementation of this could just fail if we couldn't `git checkout master`.

Sure, fair enough.

**Comment by ErikSchierboom** [comment]
I like this suggestion.

**Comment by glennj** [comment]
Or, instead of `git checkout -- .` we could do `git stash`

**Comment by ErikSchierboom** [comment]
Being able to specify the path to a prob-specs repo also allows us to finally add some tests. See https://github.com/exercism/canonical-data-syncer/issues/4. If anyone is up for adding some integration tests (which should work with the actual binary), that would be fantastic.

**Comment by ErikSchierboom** [comment]
@coriolinus @glennj There is a related issue opened in #66 and I've added [some comments](https://github.com/exercism/canonical-data-syncer/issues/66#issuecomment-714274173). I'd be interested in hearing your opinions.
