### ISSUE TITLE
Feature: Consider adding an offline mode

### ISSUE THREAD

**Issue by ee7** [exercism/canonical-data-syncer#66]
It might be useful to specify an existing `problem-specifications` directory as-is so that we can, for example:
1. Run tests on the binary in this repo without involving the network. 
1. Still use the tool when we know we have no internet connection, or a very bad one.
1. Avoid waiting for the `git fetch` (`problem-specifications` doesn't update **so** often) and/or
1. Deliberately use an older revision so that recent changes are handled incrementally.

**Comment by ErikSchierboom** [comment]
There is a similar issue open: https://github.com/exercism/canonical-data-syncer/issues/47

> Deliberately use an older revision so that recent changes are handled incrementally.

Actually, the canonical data syncer gives one the option to skip tests, so one can incrementally updated anyways.

**Comment by coriolinus** [comment]
I think it's clear that any `--offline` flag would be legal only if the user also provided the `--problem-specifications` flag as well. 

The best argument in favor of an offline mode that I can see is for the circumstance where you know you have the most current `problem-specifications`, but are literally offline or have severely limited bandwidth. I've been known to sync up my repos on my laptop, then work offline while on the train, for example. As things stand right now, I couldn't do that with the `canonical-data-syncer`: even providing it with the path to the p-s repo, it would attempt to fetch, then fail out with a git failure.

I'm not a huge fan of the idea of people deliberately using an older p-s version, but they'd have to be pretty deliberate about setting up that circumstance. Given how far this is from the default behavior, I don't mind enabling that possibility.

**Comment by ee7** [comment]
@ErikSchierboom 
> Well, the canonical data syncer does allow one to skip tests that one would prefer not handling. So in a way this is already possible.

True - I think that was the weakest argument.

@coriolinus 

> I think it's clear that any --offline flag would be legal only if the user also provided the --problem-specifications flag as well.

Yes.

> but are literally offline or have severely limited bandwidth. I've been known to sync up my repos on my laptop, then work offline while on the train, for example. 

I've done things like this too. I actually had this in mind when I made the issue, but somehow neglected to write it down. It'd also be personally convenient while I'm developing the tool (although we're not optimising for that), and while running tests of the release binary (which are upcoming).

> I'm not a huge fan of the idea of people deliberately using an older p-s version

Same here.

> but they'd have to be pretty deliberate about setting up that circumstance. Given how far this is from the default behavior, I don't mind enabling that possibility.

I'm leaning towards this too.

**Comment by ErikSchierboom** [comment]
Okay. You have me convinced. As long as its an extra flag _and_ a path to the prob-specs dir is specified, we can allow for offline mode. Will make the tests easier to write too :)

**Comment by glennj** [comment]
To me, providing a path to p-s implies "offline", so I'm not seeing why we need to separate options.

If I want to say "here's my local p-s repo AND please check that it has all the lastest content" then I'd want to specify an **online** flag.

If we say that `--problem-specifications=/path/to/...` implies offline, then the syncer could issue a warning like "It's your responsibility to keep your repo up to date".

**Comment by ee7** [comment]
@glennj wrote:
> then I'd want to specify an online flag.

Hmm, good suggestion. It's worth thinking about.

I've actually already implemented this today as `--offline`, just waiting for #65 to get merged first.

As I see it, the pros of `--probSpecDir` meaning offline:
- The expert user doesn't have to type `--offline`, or doesn't have to wait for a `fetch`

Cons:
- The less-expert user might not realise they should pass `--online`
- The expert user can forget to pass `--online`
- There are scenarios where it's bad if people don't pass `--online`, and it's harder to accidentally pass `--offline`

I'd maybe prefer to have `--online` if it was just me using the tool, but otherwise my initial sense is that the cons outweigh the pros - it's better to increase general safety than increase convenience.

What do you think? I'd also appreciate the opinion of anybody else reading this.

> If we say that --problem-specifications=/path/to/... implies offline, then the syncer could issue a warning like "It's your responsibility to keep your repo up to date".

Would this warning be issued even in quiet mode? Because there'll probably be some scripts that'll use that.

**Comment by coriolinus** [comment]
> To me, providing a path to p-s implies "offline"

Disagree. I have a local p-s repo, and it's quicker to update it than to clone it, but most of the time I won't want to have to go there and manually update it. IMO the ergonomics are best if the tool defaults to online, but has an offline mode to get around errors which would otherwise occur when actually offline.

> Either way, the biggest implementation problem is that the `-o` option is already taken

`-O`, maybe, or just have offline be a long-only flag.

**Comment by ee7** [comment]
> IMO the ergonomics are best if the tool defaults to online

Thanks for the input.

> `-O`, maybe

Yeah, maybe. But if we're entering the world of "case sensitivity for some short options" then I think I prefer:

```
-o, --offline
-v, --verbosity
-V, --version
```

> or just have offline be a long-only flag.

And in the world of "some options are long-only" I think I prefer:
```
-o, --offline
-v, --verbosity
    --version
```

which is my favourite so far. Thoughts?

**Comment by coriolinus** [comment]
I'm fine with either of those proposed schemes. I have a mild antipathy to the notion that all options must always have short forms.
